"""Build a correction-friendly reference draft from multiple ASR outputs.

    python scripts/build_reference_draft.py

A human reference transcript cannot be generated by a model — using one model's output
as its own ground truth would score every other model against that model and guarantee
it "wins". So this does not try to produce the reference. It produces the *cheapest
possible correction task* for a human.

Where two independent speech models agree word-for-word, that span is almost certainly
correct and needs no attention. Where they disagree, that span is exactly where the
human ear is required — and, not coincidentally, where the information-preservation
failures live.

Output: data/demo/meta/transcripts.md, with
  * the best available draft to edit,
  * every disagreement listed underneath as `sahara | other`,
  * the facts the scenario was designed to contain, as a checklist.

Correct the draft, then: python scripts/transcribe_demo.py --apply
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import config  # noqa: E402
from app.normalize import normalize_loose  # noqa: E402

TRANSCRIPTS = config.DEMO_META / "transcripts.md"

HEADER = """\
# Reference transcripts

**You only need to fix the parts the models disagreed on.** Everything else, two
independent speech models produced identically, so it is almost certainly right.

Under each clip:

* the **draft** — edit this block, it is what becomes the reference
* **disagreements** — where the models differ, listen and pick the truth
* **must contain** — the facts the scenario was designed around; make sure the
  draft says them, because these are what the benchmark scores

Rules:

* Write what was **actually said**, including Pidgin/Yoruba/Igbo/Hausa words and
  diacritics (ẹ ọ ṣ, tone marks) where you can.
* Do **not** tidy grammar, and do **not** translate.
* Write numbers as **spoken** ("forty five thousand", not "45,000"). The scorer
  canonicalises numbers itself, so spoken form stays honest.

When done:  `python scripts/transcribe_demo.py --apply`

---
"""


def _load(model: str) -> dict[str, str]:
    path = config.RESULTS / f"{model}.jsonl"
    out: dict[str, str] = {}
    if not path.exists():
        return out
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not row.get("error") and row.get("text"):
                out[row["audio_id"]] = row["text"].strip()
    return out


def disagreements(a: str, b: str, context: int = 3) -> list[tuple[str, str]]:
    """Spans where two transcripts differ, compared on normalized words."""
    aw, bw = a.split(), b.split()
    an, bn = normalize_loose(a).split(), normalize_loose(b).split()
    if not an or not bn:
        return []

    matcher = difflib.SequenceMatcher(None, an, bn, autojunk=False)
    spans: list[tuple[str, str]] = []
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            continue
        left = " ".join(aw[max(0, i1 - context):min(len(aw), i2 + context)])
        right = " ".join(bw[max(0, j1 - context):min(len(bw), j2 + context)])
        if left.strip() or right.strip():
            spans.append((left.strip() or "(nothing)", right.strip() or "(nothing)"))
    return spans


def agreement(a: str, b: str) -> float:
    an, bn = normalize_loose(a).split(), normalize_loose(b).split()
    if not an and not bn:
        return 1.0
    if not an or not bn:
        return 0.0
    return difflib.SequenceMatcher(None, an, bn, autojunk=False).ratio()


def must_contain(scenario: str, truth: dict) -> list[str]:
    facts: list[str] = []
    entry = truth.get(scenario, {})
    for amount in entry.get("amounts", []) or []:
        facts.append(f"amount {amount:,}")
    for ref in entry.get("references", []) or []:
        facts.append(f"reference {ref}")
    for name, value in (entry.get("fields") or {}).items():
        if name in {"amount", "amounts", "transaction_reference"}:
            continue
        if isinstance(value, list):
            for item in value:
                facts.append(f"{name}: {item}")
        elif value not in (None, ""):
            facts.append(f"{name}: {value}")
    return facts


def main() -> None:
    ap = argparse.ArgumentParser(description="Build a correction-friendly draft.")
    ap.add_argument("--primary", default="sahara", help="model used as the draft text")
    ap.add_argument("--compare", nargs="*",
                    default=["whisper_large_v3", "whisper_small"],
                    help="models compared against the primary")
    args = ap.parse_args()

    manifest = config.DATA / "manifests" / "demo.jsonl"
    if not manifest.exists():
        raise SystemExit(
            "\n[draft] data/manifests/demo.jsonl not found.\n"
            "  Run: python -m benchmark.load_dataset --source demo\n"
        )
    rows = [json.loads(l) for l in manifest.read_text(encoding="utf-8").splitlines()
            if l.strip()]

    gt_path = config.DEMO_META / "ground_truth.json"
    truth = json.loads(gt_path.read_text(encoding="utf-8")) if gt_path.exists() else {}

    spec_path = config.DEMO_META / "scenarios.json"
    spec = json.loads(spec_path.read_text(encoding="utf-8")) if spec_path.exists() else {}

    primary = _load(args.primary)
    others = {m: _load(m) for m in args.compare}
    others = {m: d for m, d in others.items() if d}

    if not primary:
        raise SystemExit(f"\n[draft] No results for {args.primary}. Run it first.\n")

    existing = {}
    if TRANSCRIPTS.exists():
        import re
        text = TRANSCRIPTS.read_text(encoding="utf-8")
        blocks = list(re.finditer(r"^### DRAFT — (\S+)\s*$", text, re.MULTILINE))
        for i, m in enumerate(blocks):
            end = blocks[i + 1].start() if i + 1 < len(blocks) else len(text)
            body = text[m.end():end].split("<!-- disagreements")[0]
            existing[m.group(1)] = body.strip()

    out = [HEADER]
    flagged = clean = 0

    for row in rows:
        aid = row["audio_id"]
        scenario = row.get("scenario_id") or aid
        meta = spec.get(scenario, {})
        draft = existing.get(aid) or primary.get(aid, "")
        if not draft:
            continue

        pairs: list[tuple[str, str, str]] = []
        best_agree = 1.0
        for model, table in others.items():
            alt = table.get(aid)
            if not alt:
                continue
            best_agree = min(best_agree, agreement(draft, alt))
            for left, right in disagreements(draft, alt):
                pairs.append((model, left, right))

        if pairs:
            flagged += 1
        else:
            clean += 1

        out.append(f"## {aid}")
        out.append(
            f"<!-- {meta.get('language_pair','?')} · {meta.get('scenario_type','?')} · "
            f"CMI {meta.get('cmi_band','?')} · noise {meta.get('noise','?')} · "
            f"model agreement {best_agree*100:.0f}% -->")
        out.append("")
        out.append(f"### DRAFT — {aid}")
        out.append("")
        out.append(draft)
        out.append("")

        if pairs:
            out.append("<!-- disagreements — listen to these spans")
            for model, left, right in pairs[:14]:
                out.append(f"     {args.primary:>16}: ...{left}...")
                out.append(f"     {model:>16}: ...{right}...")
                out.append("")
            out.append("-->")
            out.append("")

        facts = must_contain(scenario, truth)
        if facts:
            out.append("<!-- must contain:")
            for fact in facts:
                out.append(f"     - {fact}")
            out.append("-->")
        out.append("")

    TRANSCRIPTS.parent.mkdir(parents=True, exist_ok=True)
    TRANSCRIPTS.write_text("\n".join(out), encoding="utf-8")

    print(f"[draft] wrote {TRANSCRIPTS}")
    print(f"[draft] {clean} clip(s) with full model agreement, "
          f"{flagged} needing attention")
    print(f"[draft] compared {args.primary} against: {', '.join(others) or '(none)'}")
    print("\nNext: correct the DRAFT blocks, then")
    print("      python scripts/transcribe_demo.py --apply")


if __name__ == "__main__":
    main()
