"""Per-scenario information-preservation analysis.

    python scripts/failure_analysis.py

WER tells you how many words a model got wrong. It does not tell you WHICH words, and in
an institutional case only some words decide anything. This script shows, scenario by
scenario, whether each model preserved the specific facts a reviewer would act on:

    amounts        a dropped zero turns 240,000 into 24,000
    references     one wrong digit makes a dispute unlocatable
    negation       "never paid" -> "paid" inverts the case

Writes reports/downstream/FAILURE_ANALYSIS.md.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import config  # noqa: E402
from app.normalize import (  # noqa: E402
    negation_markers,
    spoken_digit_strings,
    spoken_numbers_to_values,
)

MANIFEST = config.DATA / "manifests" / "demo.jsonl"
OUT = config.REPORTS / "downstream" / "FAILURE_ANALYSIS.md"


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def main() -> None:
    manifest = {r["audio_id"]: r for r in load_jsonl(MANIFEST)}
    if not manifest:
        raise SystemExit(f"\n[failure] no manifest at {MANIFEST}\n")

    truth = json.loads((config.DEMO_META / "ground_truth.json").read_text(encoding="utf-8"))

    models: dict[str, dict[str, str]] = {}
    for path in sorted(config.RESULTS.glob("*.jsonl")):
        preds = {r["audio_id"]: r.get("text", "")
                 for r in load_jsonl(path)
                 if r["audio_id"] in manifest and not r.get("error")}
        if preds:
            models[path.stem] = preds
    if not models:
        raise SystemExit("\n[failure] no ASR results for the demo manifest\n")

    names = sorted(models)
    lines = [
        "# Information Preservation - per scenario",
        "",
        "Generated by `scripts/failure_analysis.py` from cached ASR outputs.",
        "",
        "Each cell is `preserved / expected` for facts a case reviewer would act on.",
        "A model can score a respectable WER and still fail here, because WER counts a",
        "dropped zero the same as a dropped filler word.",
        "",
    ]

    totals = {m: {"amt": [0, 0], "ref": [0, 0], "neg": [0, 0]} for m in names}

    lines += ["## Amounts", "",
              "| Scenario | Expected | " + " | ".join(f"`{m}`" for m in names) + " |",
              "|---|---|" + "|".join(["--:"] * len(names)) + "|"]
    for aid in sorted(manifest):
        scen = manifest[aid].get("scenario_id", aid)
        expected = truth.get(scen, {}).get("amounts") or []
        if not expected:
            continue
        cells = []
        for m in names:
            got = spoken_numbers_to_values(models[m].get(aid, ""))
            pool, hit = list(got), 0
            for e in expected:
                if e in pool:
                    pool.remove(e)
                    hit += 1
            totals[m]["amt"][0] += hit
            totals[m]["amt"][1] += len(expected)
            mark = "" if hit == len(expected) else " ❌"
            cells.append(f"{hit}/{len(expected)}{mark}")
        pretty = ", ".join(f"{e:,}" for e in expected)
        lines.append(f"| `{scen}` | {pretty} | " + " | ".join(cells) + " |")

    lines += ["", "## Reference numbers", "",
              "| Scenario | Expected | " + " | ".join(f"`{m}`" for m in names) + " |",
              "|---|---|" + "|".join(["--:"] * len(names)) + "|"]
    any_ref = False
    for aid in sorted(manifest):
        scen = manifest[aid].get("scenario_id", aid)
        expected = [str(r) for r in (truth.get(scen, {}).get("references") or [])]
        if not expected:
            continue
        any_ref = True
        cells = []
        for m in names:
            got = spoken_digit_strings(models[m].get(aid, ""))
            hit = sum(1 for e in expected if e in got)
            totals[m]["ref"][0] += hit
            totals[m]["ref"][1] += len(expected)
            mark = "" if hit == len(expected) else " ❌"
            cells.append(f"{hit}/{len(expected)}{mark}")
        lines.append(f"| `{scen}` | {', '.join(expected)} | " + " | ".join(cells) + " |")
    if not any_ref:
        lines.append("| _none_ | | " + " | ".join("-" for _ in names) + " |")

    lines += ["", "## Negation", "",
              "| Scenario | Expected | " + " | ".join(f"`{m}`" for m in names) + " |",
              "|---|---|" + "|".join(["--:"] * len(names)) + "|"]
    for aid in sorted(manifest):
        scen = manifest[aid].get("scenario_id", aid)
        script = truth.get(scen, {}).get("reference_script", "")
        expected = negation_markers(script) if script else 0
        if not expected:
            continue
        cells = []
        for m in names:
            kept = min(negation_markers(models[m].get(aid, "")), expected)
            totals[m]["neg"][0] += kept
            totals[m]["neg"][1] += expected
            mark = "" if kept == expected else " ❌"
            cells.append(f"{kept}/{expected}{mark}")
        lines.append(f"| `{scen}` | {expected} | " + " | ".join(cells) + " |")

    lines += ["", "## Totals", "",
              "| Model | Amounts | Reference numbers | Negation |", "|---|--:|--:|--:|"]
    for m in names:
        row = []
        for key in ("amt", "ref", "neg"):
            hit, tot = totals[m][key]
            row.append(f"{hit}/{tot} ({hit / tot * 100:.1f}%)" if tot else "-")
        lines.append(f"| `{m}` | " + " | ".join(row) + " |")

    lines += [
        "",
        "## Why this drives a product decision",
        "",
        "Amount preservation differs sharply between models **and the models fail on",
        "different scenarios**, so no single speech model is safe for financial values and",
        "swapping in a better one does not fix it. A dropped zero produces a transcript",
        "that still reads fluently, so nothing downstream can detect the error.",
        "",
        "The system therefore refuses to treat an extracted amount or reference number as",
        "settled. Both are returned in `verification_required`, the packet is held at",
        "`awaiting_confirmation`, and the value is read back to the speaker before the case",
        "can be acted on. See `HIGH_RISK_FIELDS` in `app/routing.py`.",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[failure] wrote {OUT}")
    print("\n" + "\n".join(lines[-14:]))


if __name__ == "__main__":
    main()
